AWSTemplateFormatVersion: 2010-09-09
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  PJPrefix:
    Type: String
  VPCCIDR:
    Type: String
    Default: 10.1.0.0/16
  PublicSubnetACIDR:
    Type: String
    Default: 10.1.10.0/24
  PublicSubnetCCIDR:
    Type: String
    Default: 10.1.20.0/24
  PrivateSubnetACIDR:
    Type: String
    Default: 10.1.100.0/24
  PrivateSubnetCCIDR:
    Type: String
    Default: 10.1.200.0/24
  
Resources:
# VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-vpc
# インターネットゲートウェイ
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-igw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
# サブネット
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetACIDR
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-public-subnet-A
  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCCIDR
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-public-subnet-C
  PrivateSubnetA: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: !Ref PrivateSubnetACIDR
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub ${PJPrefix}-private-subnet-a
  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: !Ref PrivateSubnetCCIDR
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: !Sub ${PJPrefix}-private-subnet-c
# ルートテーブル（パブリック）
  PublicRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-public-route-A
  PublicRouteTableC:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: !Sub ${PJPrefix}-public-route-C
# ルートテーブル（プライベート）
  PrivateRouteTableA: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub ${PJPrefix}-private-route-A
  PrivateRouteTableC: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-private-route-C
# ルーティング
  PublicRouteA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicRouteC:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTableC
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTableA
  PrivateSubnetCRouteTableAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetC
      RouteTableId: !Ref PrivateRouteTableC

Outputs:
# VPC
  VPC:
    Value: !Ref VPC
    Export:
      Name: !Sub ${PJPrefix}-vpc
  VPCCIDR:
    Value: !Ref VPCCIDR
    Export:
      Name: !Sub ${PJPrefix}-vpc-cidr
# Subnet
  PublicSubnetA:
    Value: !Ref PublicSubnetA
    Export:
      Name: !Sub ${PJPrefix}-public-subnet-a
  PublicSubnetACIDR:
    Value: !Ref PublicSubnetACIDR
    Export:
      Name: !Sub ${PJPrefix}-public-subnet-a-cidr
  PublicSubnetC:
    Value: !Ref PublicSubnetC
    Export:
      Name: !Sub ${PJPrefix}-public-subnet-c
  PublicSubnetCCIDR:
    Value: !Ref PublicSubnetCCIDR
    Export:
      Name: !Sub ${PJPrefix}-public-subnet-c-cidr
  PrivateSubnetA:
    Value: !Ref PrivateSubnetA
    Export:
      Name: !Sub ${PJPrefix}-private-subnet-a
  PrivateSubnetACIDR:
    Value: !Ref PrivateSubnetACIDR
    Export:
      Name: !Sub ${PJPrefix}-private-subnet-a-cidr
  PrivateSubnetC:
    Value: !Ref PrivateSubnetC
    Export:
      Name: !Sub ${PJPrefix}-private-subnet-c
  PrivateSubnetCCIDR:
    Value: !Ref PrivateSubnetCCIDR
    Export:
      Name: !Sub ${PJPrefix}-private-subnet-c-cidr
# Route
  PublicRouteTableA:
    Value: !Ref PublicRouteTableA
    Export:
      Name: !Sub ${PJPrefix}-public-route-a
  PublicRouteTableC:
    Value: !Ref PublicRouteTableC
    Export:
      Name: !Sub ${PJPrefix}-public-route-c
  PrivateRouteTableA:
    Value: !Ref PrivateRouteTableA
    Export:
      Name: !Sub ${PJPrefix}-private-route-a
  PrivateRouteTableC:
    Value: !Ref PrivateRouteTableC
    Export:
      Name: !Sub ${PJPrefix}-private-route-c